# Generated by Django 3.2.7 on 2021-09-26 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabotyaga',
            name='familiya_rabot',
        ),
        migrations.RemoveField(
            model_name='rabotyaga',
            name='imya_rabot',
        ),
        migrations.AddField(
            model_name='rabotyaga',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='dungeon.user'),
            preserve_default=False,
        ),
    ]
