# Generated by Django 3.2.7 on 2021-09-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0002_auto_20210926_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_rabot', models.CharField(choices=[('sv', 'svarka'), ('mn', 'montaj'), ('cr', 'crovlya')], max_length=2)),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Manadger',
        ),
        migrations.DeleteModel(
            name='Rabotyaga',
        ),
    ]
