# Generated by Django 3.2.7 on 2021-09-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0003_auto_20210926_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
