# Generated by Django 3.2.7 on 2021-09-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0004_alter_zayavka_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='extra_info',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
