# Generated by Django 3.2.7 on 2021-09-26 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0005_auto_20210926_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='imya_clienta',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='dungeon.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='extra_info',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='tip_rabot',
            field=models.CharField(blank=True, choices=[('sv', 'svarka'), ('mn', 'montaj'), ('cr', 'crovlya')], max_length=2),
        ),
    ]
