# Generated by Django 3.2.7 on 2021-09-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0006_auto_20210926_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zayavka',
            name='imya_clienta',
        ),
    ]
