# Generated by Django 3.2.7 on 2021-09-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0007_remove_zayavka_imya_clienta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zayavka',
            name='tip_rabot',
        ),
        migrations.AddField(
            model_name='zayavka',
            name='familiya_clienta',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='imya_clienta',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
