# Generated by Django 3.2.7 on 2021-09-26 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0009_alter_zayavka_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TipRabot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_rabot', models.CharField(blank=True, max_length=30)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeon.zayavka')),
            ],
        ),
    ]
