# Generated by Django 3.2.7 on 2021-09-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0010_auto_20210927_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiprabot',
            name='tip',
        ),
        migrations.AddField(
            model_name='zayavka',
            name='tip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dungeon.tiprabot'),
            preserve_default=False,
        ),
    ]
