# Generated by Django 3.2.7 on 2021-09-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0011_auto_20210927_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zayavka',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
