# Generated by Django 3.2.7 on 2021-09-29 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0013_auto_20210927_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_client', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManadgerProx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manadger', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RabotyagaProx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rabotyaga', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='zayavka',
            options={'ordering': ['status', '-data']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manadger',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_rabotyaga',
        ),
        migrations.AddField(
            model_name='zayavka',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dungeon.clientprox'),
        ),
        migrations.AddField(
            model_name='user',
            name='manadger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dungeon.manadgerprox'),
        ),
        migrations.AddField(
            model_name='user',
            name='rabotyaga',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dungeon.rabotyagaprox'),
        ),
    ]
