# Generated by Django 3.2.7 on 2021-09-29 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0014_auto_20210929_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='manadger',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rabotyaga',
        ),
        migrations.AddField(
            model_name='clientprox',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manadgerprox',
            name='manadger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rabotyagaprox',
            name='rabotyaga',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
