# Generated by Django 3.2.7 on 2021-09-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0015_auto_20210929_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manadgerprox',
            name='is_manadger',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rabotyagaprox',
            name='is_rabotyaga',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
