# Generated by Django 3.2.7 on 2021-09-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0016_auto_20210930_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='cleent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
