# Generated by Django 3.2.7 on 2021-09-29 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0017_zayavka_cleent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='cleent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleent', to=settings.AUTH_USER_MODEL),
        ),
    ]
