# Generated by Django 3.2.7 on 2021-09-30 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0019_clientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
