# Generated by Django 3.2.7 on 2021-09-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0020_alter_clientprofile_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientProfile',
        ),
    ]
