# Generated by Django 3.2.7 on 2021-09-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0022_alter_zayavka_cleent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zayavka',
            options={'ordering': ['user', 'status', '-data']},
        ),
        migrations.AddField(
            model_name='zayavka',
            name='trudyashiysya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dungeon.rabotyagaprox'),
        ),
    ]
