# Generated by Django 3.2.7 on 2021-10-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0023_auto_20210930_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manadgerprox',
            name='manadger',
        ),
        migrations.RemoveField(
            model_name='rabotyagaprox',
            name='rabotyaga',
        ),
        migrations.RemoveField(
            model_name='zayavka',
            name='trudyashiysya',
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manadger',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_rabotyaga',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='ClientProx',
        ),
        migrations.DeleteModel(
            name='ManadgerProx',
        ),
        migrations.DeleteModel(
            name='RabotyagaProx',
        ),
    ]
