# Generated by Django 3.2.7 on 2021-10-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0024_auto_20211001_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='familiya',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='imya',
            field=models.CharField(max_length=150),
        ),
    ]
